Create: resourceAutomanageConfigurationProfileAssignmentCreateUpdate,
		Read:   resourceAutomanageConfigurationProfileAssignmentRead,,
		Update: resourceAutomanageConfigurationProfileAssignmentCreateUpdate,
		Delete: resourceAutomanageConfigurationProfileAssignmentDelete,
